### ISSUE TITLE
想知道这个算法能多大程度解决文件重复保存的问题？

### ISSUE THREAD

**Issue by houkunlin** [qiniu/qetag#37]
我这个问法可能有点模糊，我想表达的是，与MD5、SHA256摘要算法相比，这个算法在判断文件唯一性是不是表现得更好？

见到网上有文章说，存在两个内容完全不同的文件，会计算出相同的MD5，在这种场景，这个算法是不是能计算出两个不同的值？是不是会表现得比SHA256更优？

**Comment by bachue** [comment]
不会的，任何哈希算法都可能会碰撞，主要是看概率高不高。这个算法不会在哈希碰撞方面表现比 SHA1 更好的，也许能超越 MD5，但不可能超越 SHA256。
